name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-win_x64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Windows
      run: dotnet publish -c Release -r win10-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --output .\dist\win_x64
    
    - name: Prepare
      run: |
        cp .\settings_radarr.json.sample .\dist\win_x64\settings_radarr.json
        cp .\settings_sonarr.json.sample .\dist\win_x64\settings_sonarr.json
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: win_x64
        path: .\dist\win_x64
        retention-days: 1
        
        
  build-linux_x64:
    runs-on: ubuntu-latest
    needs: [build-win_x64]

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Windows
      run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true --output ./dist/linux_x64
        
    - name: Prepare
      run: |
        cp ./settings_radarr.json.sample ./dist/linux_x64/settings_radarr.json
        cp ./settings_sonarr.json.sample ./dist/linux_x64/settings_sonarr.json
    
    - name: 'Download Windows Artifact'
      uses: actions/download-artifact@v2
      with:
        name: win_x64
        path: dist/win_x64
    
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M')"
        
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ steps.github_release.outputs.changelog }}
        tag_name: ${{ steps.date.outputs.date }}
        files: |
          dist/win_x64
          dist/linux_x64
      
      
      
